lesson13
Feldmar/js-home-tasks-boltach pull request #12
Opened 2022-03-31 20:29 UTC by Feldmar

2022-04-17 20:42 UTC, instinct-it-academy requested changes
Добрый вечер, задание пока что на доработку, обратите внимание на комментарии.

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/canvas/index.html
> +  <link href="style.css" rel="stylesheet" type="text/css" />
Вы подключаете стили, но их в принципе не используете и они отсутствуют в задании. Пожалуйста проверяйте код перед созданием PR

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/canvas/index.html
> +  <script src="/script.js"></script>
в обоих html указаны не коррекные пути для файлов, должны быть указаны относительные пути
![image](https://user-images.githubusercontent.com/29653615/163731045-5ef594d3-a2b0-456e-b1b2-cb7dc03db6f5.png)

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/canvas/script.js
> +function arrows() {
![image](https://user-images.githubusercontent.com/29653615/163731181-8e4e7a6d-acdd-4ed3-b8d8-443f83b89aa1.png)
обратите внимание на именование, лучше либо через глагол, либо через tick+что-то характирезующие

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/canvas/script.js
> +	BigClock();
Big - лучше заменить на что-то характирезующие тип часов

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/canvas/script.js
> +'use strict';
![image](https://user-images.githubusercontent.com/29653615/163731271-8aeb42c4-2b89-48d3-822f-041ccf426ba6.png)
обратите внимание на форматирование, отступы должны равнятся 2 пробелам

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/svg/script.js
> +	  numHours = 12;
обратите внимание на то что констатны должны быть описаны согласно условию задания, так же пожалуйста добавляйте var к каждой переменной

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/svg/script.js
> +	angleValue += distanceOfDigits;
обратите внимание на форматирование

2022-04-17 20:42 UTC, instinct-it-academy commented on lesson-13-timers-svg-canvas/svg/script.js
> +
для задание необходим рефакторинг, разбейте пожалуйста создание и запуск часов на отдельные, небольшие и чистые фукнции

2022-04-30 21:33 UTC, Feldmar commented on lesson-13-timers-svg-canvas/canvas/index.html
> +  <link href="style.css" rel="stylesheet" type="text/css" />
Здравствуйте, исправила.

2022-04-30 21:33 UTC, Feldmar commented on lesson-13-timers-svg-canvas/canvas/index.html
> +  <script src="/script.js"></script>
Исправлено.

2022-04-30 21:33 UTC, Feldmar commented on lesson-13-timers-svg-canvas/canvas/script.js
> +function arrows() {
Использовала tick, спасибо.

2022-04-30 21:34 UTC, Feldmar commented on lesson-13-timers-svg-canvas/canvas/script.js
> +	BigClock();
Исправлено.

2022-04-30 21:37 UTC, Feldmar commented on lesson-13-timers-svg-canvas/canvas/script.js
> +'use strict';
Исправлено, касательно конкретно этой проблемы, я нашла в чем причина и как не странно это именно табы. Буквально если таб 2 пробела, и по ошибке его поставить вместо пробела, а затем убрать один из этих пробелов при помощи backspace выходят такие приколы)

2022-04-30 21:37 UTC, Feldmar commented on lesson-13-timers-svg-canvas/svg/script.js
> +	  numHours = 12;
Исправлено.

2022-04-30 21:38 UTC, Feldmar commented on lesson-13-timers-svg-canvas/svg/script.js
> +
Исправлено, старалась максимально логично расположить функции, надеюсь такой вариант будет приемлем, спасибо.

2022-05-28 20:27 UTC, instinct-it-academy approved these changes
Добрый вечер, принято

2022-05-28 20:27 UTC, merged