Lesson 3 code execution
Feldmar/js-home-tasks-boltach pull request #2
Opened 2022-02-10 18:09 UTC by Feldmar

2022-02-13 12:11 UTC, instinct-it-academy requested changes
Добрый день, задание пока что на доработку. Обратите внимание на комментарии и пример выполнения задания.

2022-02-13 12:11 UTC, instinct-it-academy commented on .vscode/settings.json
> +{
Конфигурационные файлы ide не должны попадать в репозиторий, проверяйте пожалуйста этот момент когда создайте PR

2022-02-13 12:11 UTC, instinct-it-academy commented on .vscode/settings.json
> +{
решается через .gitignore на уровне репозитория

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +var a = Math.max.apply(Math, Object.values(cooperator));
Можете описать зачем в данном случае применён apply и как работаем с контекстом в данной ситуации?

Я больше к вопросу использования пройденного материала. Код выше корректен и принят при условии понимания работы подхода выше. Если не до конца понятно как работает, то лучше было найти максимум через промежуточную переменную.

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +
крайне много пустых строк, обычно добавляем их только для улучшения читаемости кода. В данном случае при корректных отступах всё будет хорошо читаться.

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +    } else {
![image](https://user-images.githubusercontent.com/29653615/153752227-adb48704-ee3e-43d9-ada8-a2f3334adad9.png)
не нужно использовать else если ничего не делаете внутри данной инструкции, актуально для всех подобных ситуаций

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +        }
нет необходимости проверять что-то кроме number, наша задача найти среди значений числа и увеличить их. Кроме строк мы можем встретить любой другой тип данных и мы никак по условию задания не должны среагировать на них

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +       if (qwe == '' || qwe === null || isNaN(qwe))  // я знаю что тут нужны фигурные скобки, но с ними не работает(
нужны ))) И скобки не должны влиять по сути ни на что и проблема обычно не в них. Тут 2 момента:
- попробуйте убрать проверку в условие цикла, т.е. уйти от бесконечного цикла и необходимости в break;
- сделать корректное форматирование, добавить {}, корректные скобки, убрать пустые строки.

обратите внимание на пример выполнения задания

2022-02-13 12:11 UTC, instinct-it-academy commented on lesson-3-code-execution/script.js
> +function consider() {
в данном случае нет необходимости в функции т.к. у нас нет ни одного бенифита, который мы бы получили от использования функции в данном контексте. Доставайте код наружу )

2022-02-13 15:13 UTC, Feldmar commented
Здравствуйте, я проработала ошибки в прошлом домашнем задании.
Мне нужно вам кидать новый пулл реквест или нет? Просто я не вижу
что-бы коммиты в текущем добавились.
Все пояснения я подробно расписала в комментариях внутри скрипта, спасибо
что даете возможность понять как лучше сделать и доработать))

https://github.com/Feldmar/js-home-tasks-boltach/tree/lesson-3-code-execution

вс, 13 февр. 2022 г. в 15:11, instinct-it-academy ***@***.***
>:

> ***@***.**** requested changes on this pull request.
>
> Добрый день, задание пока что на доработку. Обратите внимание на
> комментарии и пример выполнения задания.
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805323932>
> :
>
> > @@ -0,0 +1,93 @@
> +"use strict";
>
> пожалуйста каждую задачу в отдельный файл
> ------------------------------
>
> In .vscode/settings.json
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324107>
> :
>
> > @@ -0,0 +1,3 @@
> +{
>
> Конфигурационные файлы ide не должны попадать в репозиторий, проверяйте
> пожалуйста этот момент когда создайте PR
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324424>
> :
>
> > +"use strict";
> +
> +//Задание №1
> +
> +var cooperator = {
> +
> +'Anna': 29,
> +'Serg': 35,
> +'Elena': 1,
> +'Anton': 99
> +
> +};
> +
> +function employee() {
> +
> +var a = Math.max.apply(Math, Object.values(cooperator));
>
> Можете описать зачем в данном случае применён apply и как работаем с
> контекстом в данной ситуации?
>
> Я больше к вопросу использования пройденного материала. Код выше корректен
> и принят при условии понимания работы подхода выше. Если не до конца
> понятно как работает, то лучше было найти максимум через промежуточную
> переменную.
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324572>
> :
>
> > +
> +var cooperator = {
> +
> +'Anna': 29,
> +'Serg': 35,
> +'Elena': 1,
> +'Anton': 99
> +
> +};
> +
> +function employee() {
> +
> +var a = Math.max.apply(Math, Object.values(cooperator));
> +
> +for (var name in cooperator) {
> +
>
> крайне много пустых строк, обычно добавляем их только для улучшения
> читаемости кода. В данном случае при корректных отступах всё будет хорошо
> читаться.
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324630>
> :
>
> > +'Elena': 1,
> +'Anton': 99
> +
> +};
> +
> +function employee() {
> +
> +var a = Math.max.apply(Math, Object.values(cooperator));
> +
> +for (var name in cooperator) {
> +
> +    if (a === cooperator[name]) {
> +
> +        console.log('Cотрудник который выполнил больше всех задач: ' + name );
> +
> +    } else {
>
> [image: image]
> <https://user-images.githubusercontent.com/29653615/153752227-adb48704-ee3e-43d9-ada8-a2f3334adad9.png>
> не нужно использовать else если ничего не делаете внутри данной
> инструкции, актуально для всех подобных ситуаций
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324774>
> :
>
> > +        } else if (typeof image[key] === "string") {
> +
> +            image[key] = "amazing image";
> +
> +        }
>
> нет необходимости проверять что-то кроме number, наша задача найти среди
> значений числа и увеличить их. Кроме строк мы можем встретить любой другой
> тип данных и мы никак по условию задания не должны среагировать на них
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805325139>
> :
>
> > +    console.log(Object.values(image));
> +}
> +
> +multiplyNumeric(image);
> +
> +//Задание №3 (которое надо было наверное делать не через функцию видимо)
> +
> +function consider() {
> +
> +    var calc = [];
> +
> +    while (true) {
> +
> +      var qwe = prompt('Введите число', '');
> +
> +       if (qwe == '' || qwe === null || isNaN(qwe))  // я знаю что тут нужны фигурные скобки, но с ними не работает(
>
> нужны ))) И скобки не должны влиять по сути ни на что и проблема обычно не
> в них. Тут 2 момента:
>
>    - попробуйте убрать проверку в условие цикла, т.е. уйти от
>    бесконечного цикла и необходимости в break;
>    - сделать корректное форматирование, добавить {}, корректные скобки,
>    убрать пустые строки.
>
> обратите внимание на пример выполнения задания
> ------------------------------
>
> In lesson-3-code-execution/script.js
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805325282>
> :
>
> > +            image[key] = image[key] * 2;
> +
> +        } else if (typeof image[key] === "string") {
> +
> +            image[key] = "amazing image";
> +
> +        }
> +    }
> +    console.log(Object.values(image));
> +}
> +
> +multiplyNumeric(image);
> +
> +//Задание №3 (которое надо было наверное делать не через функцию видимо)
> +
> +function consider() {
>
> в данном случае нет необходимости в функции т.к. у нас нет ни одного
> бенифита, который мы бы получили от использования функции в данном
> контексте. Доставайте код наружу )
> ------------------------------
>
> In .vscode/settings.json
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324139>
> :
>
> > @@ -0,0 +1,3 @@
> +{
>
> решается через .gitignore на уровне репозитория
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#pullrequestreview-880972129>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVOTD6TCBYMZJRUIUCX4YYTU26NWJANCNFSM5OBSASJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-02-13 19:30 UTC, Feldmar commented
Доброй ночи, домашнее задание готово, пулл реквест я скинула. Спасибо)
P.S. А можно больше не так сложно, пожалуйста)
https://github.com/Feldmar/js-home-tasks-boltach/tree/lesson-4-closures

вс, 13 февр. 2022 г. в 18:12, Фелд Миллер ***@***.***>:

> Здравствуйте, я проработала ошибки в прошлом домашнем задании.
> Мне нужно вам кидать новый пулл реквест или нет? Просто я не вижу
> что-бы коммиты в текущем добавились.
> Все пояснения я подробно расписала в комментариях внутри скрипта, спасибо
> что даете возможность понять как лучше сделать и доработать))
>
>
> https://github.com/Feldmar/js-home-tasks-boltach/tree/lesson-3-code-execution
>
> вс, 13 февр. 2022 г. в 15:11, instinct-it-academy <
> ***@***.***>:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Добрый день, задание пока что на доработку. Обратите внимание на
>> комментарии и пример выполнения задания.
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805323932>
>> :
>>
>> > @@ -0,0 +1,93 @@
>> +"use strict";
>>
>> пожалуйста каждую задачу в отдельный файл
>> ------------------------------
>>
>> In .vscode/settings.json
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324107>
>> :
>>
>> > @@ -0,0 +1,3 @@
>> +{
>>
>> Конфигурационные файлы ide не должны попадать в репозиторий, проверяйте
>> пожалуйста этот момент когда создайте PR
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324424>
>> :
>>
>> > +"use strict";
>> +
>> +//Задание №1
>> +
>> +var cooperator = {
>> +
>> +'Anna': 29,
>> +'Serg': 35,
>> +'Elena': 1,
>> +'Anton': 99
>> +
>> +};
>> +
>> +function employee() {
>> +
>> +var a = Math.max.apply(Math, Object.values(cooperator));
>>
>> Можете описать зачем в данном случае применён apply и как работаем с
>> контекстом в данной ситуации?
>>
>> Я больше к вопросу использования пройденного материала. Код выше
>> корректен и принят при условии понимания работы подхода выше. Если не до
>> конца понятно как работает, то лучше было найти максимум через
>> промежуточную переменную.
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324572>
>> :
>>
>> > +
>> +var cooperator = {
>> +
>> +'Anna': 29,
>> +'Serg': 35,
>> +'Elena': 1,
>> +'Anton': 99
>> +
>> +};
>> +
>> +function employee() {
>> +
>> +var a = Math.max.apply(Math, Object.values(cooperator));
>> +
>> +for (var name in cooperator) {
>> +
>>
>> крайне много пустых строк, обычно добавляем их только для улучшения
>> читаемости кода. В данном случае при корректных отступах всё будет хорошо
>> читаться.
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324630>
>> :
>>
>> > +'Elena': 1,
>> +'Anton': 99
>> +
>> +};
>> +
>> +function employee() {
>> +
>> +var a = Math.max.apply(Math, Object.values(cooperator));
>> +
>> +for (var name in cooperator) {
>> +
>> +    if (a === cooperator[name]) {
>> +
>> +        console.log('Cотрудник который выполнил больше всех задач: ' + name );
>> +
>> +    } else {
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/29653615/153752227-adb48704-ee3e-43d9-ada8-a2f3334adad9.png>
>> не нужно использовать else если ничего не делаете внутри данной
>> инструкции, актуально для всех подобных ситуаций
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324774>
>> :
>>
>> > +        } else if (typeof image[key] === "string") {
>> +
>> +            image[key] = "amazing image";
>> +
>> +        }
>>
>> нет необходимости проверять что-то кроме number, наша задача найти среди
>> значений числа и увеличить их. Кроме строк мы можем встретить любой другой
>> тип данных и мы никак по условию задания не должны среагировать на них
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805325139>
>> :
>>
>> > +    console.log(Object.values(image));
>> +}
>> +
>> +multiplyNumeric(image);
>> +
>> +//Задание №3 (которое надо было наверное делать не через функцию видимо)
>> +
>> +function consider() {
>> +
>> +    var calc = [];
>> +
>> +    while (true) {
>> +
>> +      var qwe = prompt('Введите число', '');
>> +
>> +       if (qwe == '' || qwe === null || isNaN(qwe))  // я знаю что тут нужны фигурные скобки, но с ними не работает(
>>
>> нужны ))) И скобки не должны влиять по сути ни на что и проблема обычно
>> не в них. Тут 2 момента:
>>
>>    - попробуйте убрать проверку в условие цикла, т.е. уйти от
>>    бесконечного цикла и необходимости в break;
>>    - сделать корректное форматирование, добавить {}, корректные скобки,
>>    убрать пустые строки.
>>
>> обратите внимание на пример выполнения задания
>> ------------------------------
>>
>> In lesson-3-code-execution/script.js
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805325282>
>> :
>>
>> > +            image[key] = image[key] * 2;
>> +
>> +        } else if (typeof image[key] === "string") {
>> +
>> +            image[key] = "amazing image";
>> +
>> +        }
>> +    }
>> +    console.log(Object.values(image));
>> +}
>> +
>> +multiplyNumeric(image);
>> +
>> +//Задание №3 (которое надо было наверное делать не через функцию видимо)
>> +
>> +function consider() {
>>
>> в данном случае нет необходимости в функции т.к. у нас нет ни одного
>> бенифита, который мы бы получили от использования функции в данном
>> контексте. Доставайте код наружу )
>> ------------------------------
>>
>> In .vscode/settings.json
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#discussion_r805324139>
>> :
>>
>> > @@ -0,0 +1,3 @@
>> +{
>>
>> решается через .gitignore на уровне репозитория
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Feldmar/js-home-tasks-boltach/pull/2#pullrequestreview-880972129>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVOTD6TCBYMZJRUIUCX4YYTU26NWJANCNFSM5OBSASJQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>> You are receiving this because you were assigned.Message ID:
>> ***@***.***>
>>
>

2022-02-17 19:42 UTC, Feldmar commented on lesson-3-code-execution/script.js
> +var a = Math.max.apply(Math, Object.values(cooperator));
К вопросу контекста в данном случае мы получаем почти то же самое что получили бы ручным циклом for но не получили потому что я написала как есть
Буквально мы получили ['29','35','1','99'], я надеюсь что понимаю это правильно.
Я знаю что если бы мы получили массив с большим количеством данных - то apply при его обработке вполне мог бы не сработать и выдать неправильный ответ.
это конечно я могла реализовать и через reduce или call но там пока что что-то сложное и не совсем понятное для меня в плане синтаксиса, так что у меня не получилось,

2022-02-26 21:20 UTC, instinct-it-academy commented
Разрешите пожалуйста конфликт, чтобы можно было смержить

2022-02-26 21:38 UTC, merged