Lesson 4 closures
Feldmar/js-home-tasks-boltach pull request #3
Opened 2022-02-13 19:27 UTC by Feldmar

2022-02-17 18:25 UTC, instinct-it-academy requested changes
Добрый вечер, само задание принято, обратите внимание на комментарии по решению, но перед тем как смержу отпишите пожалуйста ответы на вопросы, которые есть в комментариях

2022-02-17 18:25 UTC, instinct-it-academy commented on lesson-4-closures/script2.js
> +var class1 = obj.className.split(' ');
любые операции со строкой было бы хорошо делать внутри фунции, иначе теряется смысл от функции. Так же обратите внимание что Вам приходится выходить за рамки тела функции, для того чтобы прочитать class1 - функция не является чистой и это достаточно просто исправить добавив class1 внутрь функции и сделав return

2022-02-17 18:25 UTC, instinct-it-academy commented on lesson-4-closures/script2.js
> +var class1 = obj.className.split(' ');
class1 - не очень хорошее имя переменной, как вариан можно было что-то на подобии classLIst, classes, ... было бы немного чище

2022-02-17 18:25 UTC, instinct-it-academy commented on lesson-4-closures/script2.js
> +      class1.splice(i,1);
мне кажется Вам дополнительно было бы хорошо тут поработать со значением счётчика и вернуться на итерацию назад, чтобы не потерять значения т.к. мы мутируем массив и изменяем его длину

2022-02-17 19:15 UTC, Feldmar commented on lesson-4-closures/script2.js
> +      class1.splice(i,1);
Я поняла этот момент когда вы показали нам решение на занятии и до меня дошло в чем проблема, спасибо.

2022-02-17 19:15 UTC, Feldmar commented on lesson-4-closures/script2.js
> +var class1 = obj.className.split(' ');
спасибо, исправлюсь

2022-02-17 19:15 UTC, Feldmar commented on lesson-4-closures/script2.js
> +var class1 = obj.className.split(' ');
спасибо, я учту)

2022-02-17 19:15 UTC, Feldmar commented on .jshintrc
> +
к сожалению я до сих пор не нашла как это сделать в jshint поэтому пока не решу этот вопрос наверное буду стараться следить за этим внимательнее

2022-02-17 19:15 UTC, Feldmar commented on .gitignore
> +/node_modules/
Здравствуйте, у меня просто остался пакет из gulp в одной из веток, поэтому я и не убирала node_modules, что бы его не загружать в репозиторий. Сейчас я его не использую, он просто остался от старой версии, я в таком случае его уберу.

2022-02-26 21:26 UTC, instinct-it-academy approved these changes

2022-02-26 21:26 UTC, merged