Lesson 5 closures
Feldmar/js-home-tasks-boltach pull request #4
Opened 2022-02-17 18:58 UTC by Feldmar

2022-02-19 10:45 UTC, instinct-it-academy requested changes
Добрый день, п целом принято, но пока не мержу т.к. не совсем понятно то что у Вас находится в .gitignore. Сначала обсудим, после этого будем мержить

2022-02-19 10:45 UTC, instinct-it-academy commented on .gitignore
> +/.git/
и снова вопрос в чём необходимость добавлять .git в игнор, по идее она никогда не попадает в отслеживаемые?  Покажите пожалуйста на занятии как Вы работаете с репозиторием

2022-02-19 10:45 UTC, instinct-it-academy commented on lesson-5-closures/script.js
> +		for(var i = 0; i < this.bills.length; i++) {
![image](https://user-images.githubusercontent.com/29653615/154797542-3b1cf610-4ddb-4265-a90d-d719ff88ce9a.png)
обратите внимание на отступы, настройте пожалуйста ide на 2 пробела

2022-02-19 12:12 UTC, Feldmar commented on .gitignore
> +/.git/
[[](url)](https://cdn1.savepice.ru/uploads/2022/2/19/896d9287c19ec4efb911301c3cd59e93-full.png)
у меня на компьютере включено отображение абсолютно всех скрытых файлов, поэтому я посчитала это необходимым, но если вы говорите что это не нужно, окей, я очищу гит игнор

2022-02-19 12:13 UTC, Feldmar commented on lesson-5-closures/script.js
> +		for(var i = 0; i < this.bills.length; i++) {
хорошо)

2022-02-26 21:31 UTC, instinct-it-academy approved these changes

2022-02-26 21:31 UTC, instinct-it-academy commented on lesson-5-closures/script.js
> +		for(var i = 0; i < this.bills.length; i++) {
отступы всё еще не корректны, будем смотреть в след. заданиях

2022-02-26 21:31 UTC, merged